[tool.black]
line-length = 100

[tool.ruff]
line-length = 100
target-version = "py37"

[tool.ruff.lint]
extend-select = ["E501"]

[tool.ruff.lint.per-file-ignores]
"buffer/application.py" = ["E402"]
"buffer/editor_text_view.py" = ["E402"]
"buffer/editor_search_header_bar.py" = ["E402"]
"buffer/window.py" = ["E402"]
