line-length = 100
target-version = "py37"

[lint]
extend-select = ["E501"]

[lint.per-file-ignores]
"application.py" = ["E402"]
"editor_text_view.py" = ["E402"]
"editor_search_header_bar.py" = ["E402"]
"window.py" = ["E402"]
